export const KEYBOARD_KEYS_CONFIG = [
  { id: "clear", className: "key-manipulator", displayContent: "AC" },
  { id: "reverse", className: "key-operator", key_icon: "plus-minus", key_disabled: true },
  { id: "backspace", className: "key-manipulator", key_icon: "delete-left" },
  { id: "divide", className: "key-operator", key_icon: "divide", displayContent: "&#247" },
  { id: "7", className: "key-number" },
  { id: "8", className: "key-number" },
  { id: "9", className: "key-number" },
  { id: "multiply", className: "key-operator", key_icon: "xmark", displayContent: "x" },
  { id: "4", className: "key-number" },
  { id: "5", className: "key-number" },
  { id: "6", className: "key-number" },
  { id: "minus", className: "key-operator", key_icon: "minus", displayContent: "-" },
  { id: "1", className: "key-number" },
  { id: "2", className: "key-number" },
  { id: "3", className: "key-number" },
  { id: "add", className: "key-operator", key_icon: "plus", displayContent: "+" },
  { id: "000", className: "key-number triplezero" },
  { id: "0", className: "key-number" },
  { id: "decimal", className: "key-manipulator", displayContent: "•" },
  { id: "equals", className: "key-manipulator", key_icon: "equals", displayContent: "=" },
];